apfs: Add missing include directives
Fix the following build errors in apfs/btree.c:

linux/fs/apfs/btree.c: In function ‘apfs_locate_block’:
linux/fs/apfs/btree.c:38:8: error: implicit declaration of function ‘kmalloc’; did you mean ‘kvmalloc’? [-Werror=implicit-function-declaration]
  key = kmalloc(sizeof(*key), GFP_KERNEL);
        ^~~~~~~
        kvmalloc
linux/fs/apfs/btree.c:38:6: warning: assignment to ‘struct apfs_key *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  key = kmalloc(sizeof(*key), GFP_KERNEL);
      ^
linux/fs/apfs/btree.c:65:2: error: implicit declaration of function ‘kfree’; did you mean ‘kvfree’? [-Werror=implicit-function-declaration]
  kfree(key);
  ^~~~~
  kvfree
linux/fs/apfs/btree.c: In function ‘apfs_alloc_query’:
linux/fs/apfs/btree.c:87:8: warning: assignment to ‘struct apfs_query *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  query = kmalloc(sizeof(*query), GFP_KERNEL);
        ^
linux/fs/apfs/btree.c:96:7: warning: assignment to ‘struct apfs_key *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  curr = kmalloc(sizeof(*curr), GFP_KERNEL);

Signed-off-by: Gabriel Krisman Bertazi <krisman@collabora.co.uk>
Signed-off-by: Ernesto A. Fernández <ernesto.mnd.fernandez@gmail.com>